<?php
/**
 * BSS Commerce Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://bsscommerce.com/Bss-Commerce-License.txt
 *
 * @category   BSS
 * @package    Hyva_BssAdvancedHidePrice
 * @author     Extension Team
 * @copyright  Copyright (c) 2023-present BSS Commerce Co. ( http://bsscommerce.com )
 * @license    http://bsscommerce.com/Bss-Commerce-License.txt
 */

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HeroiconsOutline;
use Hyva\Theme\ViewModel\HeroiconsSolid;
use Hyva\Theme\ViewModel\ProductCompare;
use Hyva\Theme\ViewModel\ProductListItem;
use Hyva\Theme\ViewModel\ProductPage;
use Hyva\Theme\ViewModel\Wishlist;
use Magento\Catalog\Block\Product\AbstractProduct;
use Magento\Catalog\Helper\Output as CatalogOutputHelper;
use Magento\Catalog\ViewModel\Product\OptionsData as ProductOptionsData;
use Magento\Framework\Escaper;

use Hyva\Theme\ViewModel\Modal as HyvaThemeViewModelModal;
use Hyva\BssAdvancedHidePrice\ViewModel\Helper as ViewModelHelper;

// phpcs:disable Magento2.Templates.ThisInTemplate.FoundHelper
// phpcs:disable Generic.Files.LineLength.TooLong

/** @var AbstractProduct $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */

/** @var ProductPage $productViewModel */
$productViewModel = $viewModels->require(ProductPage::class);

/** @var ProductListItem $productListItemViewModel */
$productListItemViewModel = $viewModels->require(ProductListItem::class);

/** @var CatalogOutputHelper $catalogOutputHelper */
$catalogOutputHelper = $viewModels->require(ViewModelHelper::class)->getCatalogHelper();

/** @var ProductCompare $compareViewModel */
$compareViewModel = $viewModels->require(ProductCompare::class);
/** @var Wishlist $wishlistViewModel */
$wishlistViewModel = $viewModels->require(Wishlist::class);

/** @var HeroiconsOutline $heroicons */
$heroicons = $viewModels->require(HeroiconsOutline::class);

/** @var HeroiconsSolid $heroiconsSolid */
$heroiconsSolid = $viewModels->require(HeroiconsSolid::class);

$productOptionsViewmodel = $viewModels->require(ProductOptionsData::class);

/** @varHyvaThemeViewModelModal $modalViewModel */
$modalViewModel = $viewModels->require(HyvaThemeViewModelModal::class);

/** @var Magento\Catalog\Model\Product $product */
$product = $block->getData('product');
$imageDisplayArea = $block->getData('image_display_area');
$templateType = $block->getData('template_type');
$viewMode = $block->getData('view_mode');
$showDescription = $block->getData('show_description');
$showAddToWishlist = $wishlistViewModel->isEnabled();
$showAddToCompare = $compareViewModel->showInProductList();
$viewIsGrid = $viewMode === 'grid';

if (!$product) {
    return '';
}
$productId = $product->getId();
$options   = $productOptionsViewmodel->getOptionsData($product);
$uniqueId = '_' . uniqid();

$hideDetails       = $block->getData('hide_details') ?: false;
$hideRatingSummary = $block->getData('hide_rating_summary') ?: false;

$imageCustomAttributes = $product->getData('image_custom_attributes')
    ?? $block->getData('image_custom_attributes')
    ?? [];

$modal = $modalViewModel->createModal();
?>

<?php if ($product->isSaleable()): ?>
<form method="post"
      action="<?= $escaper->escapeUrl($productViewModel->getAddToCartUrl($product, ['useUencPlaceholder' => true])) ?>"
      class="relative item product product-item product_addtocart_form card card-interactive flex flex-col w-full <?= $viewIsGrid ? '' : 'md:flex-row' ?>"
    <?php if ($product->getOptions()): ?>
        enctype="multipart/form-data"
    <?php endif; ?>
>
    <?= /** @noEscape */ $block->getBlockHtml('formkey') ?>
    <input type="hidden" name="product" value="<?= (int)$productId ?>"/>
    <?php foreach ($options as $optionItem): ?>
        <input type="hidden"
               name="<?= $escaper->escapeHtml($optionItem['name']) ?>"
               value="<?= $escaper->escapeHtml($optionItem['value']) ?>">
    <?php endforeach; ?>
    <?php else: ?>
    <div class="item product product-item card card-interactive flex flex-col w-full relative <?= $viewIsGrid ? '' : 'md:flex-row' ?>">
        <?php endif; ?>
        <?php /* Product Image */ ?>
        <a href="<?= $escaper->escapeUrl($product->getProductUrl()) ?>"
           class="product photo product-item-photo block mx-auto mb-3 <?= $viewIsGrid ? '' : 'md:w-2/6 md:mb-0 md:mr-5' ?>"
           tabindex="-1"
        >
            <?= $block->getImage($product, $imageDisplayArea)
                ->setTemplate('Magento_Catalog::product/list/image.phtml')
                ->setData('custom_attributes', $imageCustomAttributes)
                ->setProductId($productId)
                ->toHtml(); ?>
        </a>
        <div class="product-info flex flex-col grow">
            <?php $productNameStripped = $block->stripTags($product->getName(), null, true); ?>
            <div class="mt-2 mb-1 items-center justify-center text-primary font-semibold text-lg text-center <?= $viewIsGrid ? '' : 'md:text-left' ?>">
                <a class="product-item-link"
                   href="<?= $escaper->escapeUrl($product->getProductUrl()) ?>">
                    <?= /* @noEscape */ $catalogOutputHelper->productAttribute($product, $product->getName(), 'name') ?>
                </a>
            </div>

            <?php if (!$hideRatingSummary): ?>
                <div class="hidden py-1 mx-auto <?= $viewIsGrid ? '' : 'md:mx-0 md:w-auto' ?>">
                    <?= $block->getReviewsSummaryHtml($product, 'short') ?>
                </div>
            <?php endif; ?>

            <?php if ($product->isAvailable() && !$hideDetails): ?>
                <?= $block->getProductDetailsHtml($product) ?>
            <?php endif; ?>

            <script>
                function initPriceBox_<?= /** @noEscape */ $uniqueId ?>()
                {
                    return {
                        updatePrice(priceData) {
                            const regularPriceLabel = this.$root.querySelector('.normal-price .price-label');
                            const regularPriceElement = this.$root.querySelector('.normal-price [data-price-type=finalPrice].price-wrapper .price');
                            const basePriceElement = this.$root.querySelector('.normal-price [data-price-type=basePrice].price-wrapper .price');
                            if (priceData.finalPrice.amount < priceData.oldPrice.amount) {
                                regularPriceLabel.classList.add('hidden');
                            } else {
                                regularPriceLabel.classList.remove('hidden');
                            }
                            regularPriceElement.innerText = hyva.formatPrice(priceData.finalPrice.amount);
                            basePriceElement && (basePriceElement.innerText = hyva.formatPrice(priceData.basePrice.amount));
                        }
                    }
                }
            </script>
            <div class="pt-1 text-gray-900 text-center"
                 x-data="initPriceBox_<?= /** @noEscape */ $uniqueId ?>()"
                 @update-prices-<?= (int)$productId ?>.window="updatePrice($event.detail);"
            >
                <?= /* @noEscape */ $productListItemViewModel->getProductPriceHtml($product) ?>
            </div>
        </div>
        <?php if ($showAddToWishlist): ?>
            <button x-data="initWishlist()"
                    @click.prevent="addToWishlist(<?= (int)$productId ?>)"
                    aria-label="<?= $escaper->escapeHtmlAttr(__('Add to Wish List')) ?>"
                    type="button"
                    class="absolute top-4 rounded-full w-9 h-9 bg-gray-200 p-0 border-0 inline-flex shrink-0 items-center justify-center text-gray-500 hover:text-red-600 ml-2">
                <?= $heroiconsSolid->heartHtml("w-5 h-5", 25, 25) ?>
            </button>
        <?php endif; ?>
        <?php if ($product->isSaleable()): ?>
</form>
<?php else: ?>
    </div>
<?php endif; ?>

<?php if ($showDescription): ?>
    <div class="mt-2 mb-1 items-center justify-center text-primary text-center <?= $viewIsGrid ? '' : 'md:text-left' ?>">
        <?= /* @noEscape */ $productViewModel->getShortDescriptionForProduct($product) ?>
    </div>
<?php endif; ?>

<style>
    .btn-primary, .bg-primary {
        background: #555656 !important;
    }
    .btn-primary:hover, .bg-primary:hover {
        background: #555656 !important;
    }
    .category-image > img {
        height: 50vh;
    }
</style>
