<?php
/**
 * BSS Commerce Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://bsscommerce.com/Bss-Commerce-License.txt
 *
 * @category   BSS
 * @package    Hyva_BssProductLabel
 * @author     Extension Team
 * @copyright  Copyright (c) 2017-2022 BSS Commerce Co. ( http://bsscommerce.com )
 * @license    http://bsscommerce.com/Bss-Commerce-License.txt
 */
?>
<?php
// @codingStandardsIgnoreFile
use Bss\ProductLabel\Block\Label;
/** @var Label $block */
$labelData = $block->getLabelData();
$productId = $block->getProduct()->getId();

?>
<?php if (!empty($labelData)): ?>
    <div class="bss-label-productlist">
        <?php foreach ($labelData as $imageData): ?>
            <div class='label-image bss-label-product'
                 data-label-product-id='<?php echo $imageData['product_id'] ?>'
                 is-main-product='<?php echo $imageData['product_id'] == $productId ? 'true' : 'false' ?>'
                 data-display="<?php echo $imageData['product_id'] == $productId ? 'block' : 'none' ?>"
                 data-background-image="<?php echo $imageData['image'] ?>" data-width="<?php echo $imageData['width'] ?>%"
                 data-height="<?php echo $imageData['height'] ?>%" data-top="<?php echo $imageData['top'] ?>%"
                 data-left="<?php echo $imageData['left'] ?>%" data-priority="<?php echo $imageData['priority'] ?>">
            </div>
        <?php endforeach; ?>
    </div>
<?php endif; ?>
