<?php
/**
 * BSS Commerce Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://bsscommerce.com/Bss-Commerce-License.txt
 *
 * @category   BSS
 * @package    Hyva_BssProductLabel
 * @author     Extension Team
 * @copyright  Copyright (c) 2017-2022 BSS Commerce Co. ( http://bsscommerce.com )
 * @license    http://bsscommerce.com/Bss-Commerce-License.txt
 */
?>

<script>
    window.addEventListener('configurable-selection-changed', e => {
        var productId = e.detail.productIndex;
        var parentProductId = e.detail.productId;
        var itemElement = document.getElementsByClassName("product-image-container-" + parentProductId)[0];
        var labelImage = document.querySelectorAll('[data-label-product-id="' + productId + '"]');
        var parentLabelImage = document.querySelector('[data-label-product-id="' + parentProductId + '"]');
        if (parentLabelImage !== null) {
            parentLabelImage.style.display = 'none';
            var parentDiv = parentLabelImage.parentNode;
        } else {
            if (labelImage.length > 0) {
                labelImage.forEach(function (labelImage) {
                    appendLabelChild(labelImage,parentProductId);
                })
            }
        }
        if (parentDiv !== null) {
            activeLabel(productId, itemElement);
        }
    });

    function appendLabelChild(labelImage, parentProductId) {
        const itemElement = document.getElementsByClassName("product-image-container-" + parentProductId)[0];
        if (typeof (itemElement) != 'undefined' && itemElement != null) {
            itemElement.style.position = 'relative';
            itemElement.appendChild(labelImage.parentElement);
        }
    }

    function activeLabel(product_id, parentDiv) {
        const labelImage = parentDiv.querySelectorAll('.label-image');
        labelImage.forEach(function (labelImage) {
            var productId = labelImage.getAttribute('data-label-product-id');
            if (typeof productId != 'undefined' && productId === product_id) {
                labelImage.style.display = 'block';
            } else {
                labelImage.style.display = 'none';
            }
        })
    }
</script>
