<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

$element = $this->getElement();
$blockName = $element->getBlockName();
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$blocks = $objectManager->get('\Magento\Cms\Block\Block');
?>
<?php if ($blockName) { ?>
	<div class="mgz-element-custom-block-<?= $blockName ?>">
        <?= $blocks->setBlockId($blockName)->toHtml(); ?>
	</div>
<?php } ?>