<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HeroiconsSolid;
use Hyva\Theme\ViewModel\Navigation;
use Magento\Framework\View\Element\Template;
use Magento\Framework\Escaper;
use Magento\Cms\Block\Block as CmsBlock;

/** @var Template $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */

// phpcs:disable Generic.Files.LineLength.TooLong

/** @var Navigation $viewModelNavigation */
$viewModelNavigation = $viewModels->require(Navigation::class, $block);

/** @var HeroiconsSolid $heroiconsSolid */
$heroiconsSolid = $viewModels->require(HeroiconsSolid::class);

$uniqueId = '_' . uniqid();

// Order is important here: 1. build the menu data, 2. then set the cache tags from the view model identities
$menuItems = $viewModelNavigation->getNavigation(4);
$block->setData('cache_tags', $viewModelNavigation->getIdentities());

?>
<div x-data="initMenuDesktop<?= $escaper->escapeHtml($uniqueId) ?>()"
     class="z-20 order-2 sm:order-1 lg:order-2 navigation hidden lg:flex"
>
    <!-- desktop -->
    <div x-ref="nav-desktop"
         @load.window="setActiveMenu($root)"
         class="justify-between items-center mx-auto w-full max-w-7xl"
    >
        <nav aria-label="<?= $escaper->escapeHtmlAttr(__('Main menu')) ?>">
            <ul class="flex flex-wrap justify-center">
                <?php foreach ($menuItems as $index => $itemLevel1): ?>
                    <?php $singleItems = []; ?>
                    <li class="level-0 flex items-center p-1 border-b-2 border-transparent transition transition-colors duration-500 group xl:p-2 hover:border-gray-200 focus-within:border-gray-200"
                         @mouseover.stop="hoverTopPosition = $event.currentTarget.offsetTop +
$event.currentTarget.getBoundingClientRect().height"
                    >
                        <a href="<?= $escaper->escapeUrl($itemLevel1['url']) ?>"
                           @focus="hoverTopPosition = $event.currentTarget.parentNode.offsetTop +
$event.currentTarget.parentNode.getBoundingClientRect().height"
                           title="<?= $escaper->escapeHtmlAttr($itemLevel1['name']) ?>"
                           class="level-0 block p-2 text-base text-gray-200 whitespace-nowrap">
                            <span><?= $escaper->escapeHtml($itemLevel1['name']) ?></span>
                            <?php if (!empty($itemLevel1['childData'])): ?>
                                <span class="inline items-center">
                                    <?= $heroiconsSolid->chevronDownHtml('w-5 h-5 inline', 25, 25, ['aria-hidden' =>
'true']) ?>
                                </span>
                            <?php endif; ?>
                        </a>
                        <?php if (!empty($itemLevel1['childData'])): ?>
                            <div class="absolute left-0 top-full z-10 -mt-3 w-full bg-white opacity-0
transition-opacity ease-out pointer-events-none group-hover:opacity-100 focus-within:opacity-100
group-hover:pointer-events-auto"
                                 :style="`margin-top: 0; top: ${hoverTopPosition}px;`"
                            >
                                <div class="flex justify-between mt-4 mb-8">
                                    <?php
                                    $catIdLvl1    = ($pos = strrpos($itemLevel1['id'], '-')) !== false
                                        ? substr($itemLevel1['id'], $pos + 1)
                                        : 0;
                                    $cmsBlockHtml = $catIdLvl1
                                        ? $this->getLayout()
                                               ->createBlock(CmsBlock::class)
                                               ->setBlockId('megamenu_block_left_cat' . $catIdLvl1)
                                               ->toHtml()
                                        : '';

                                    if (! empty($cmsBlockHtml)): ?>
                                    <div class="max-w-xs 2xl:block">
                                        <?= /** @noEscape */ $cmsBlockHtml ?>
                                    </div>
                                    <?php endif; ?>
                                    <div class="mx-auto">
                                        <ul class="grid flex-1 grid-cols-4 gap-y-4 gap-x-8 p-4">
                                            <?php foreach ($itemLevel1['childData'] as $itemLevel2): ?>
                                                <?php if (empty($itemLevel2['childData'])): ?>
                                                    <?php $singleItems[] = $itemLevel2 ?>
                                                    <?php continue; ?>
                                                <?php endif; ?>
                                                <li class="level-1 min-w-48">
                                                    <a href="<?= $escaper->escapeUrl($itemLevel2['url']) ?>"
                                                       title="<?= $escaper->escapeHtmlAttr($itemLevel2['name']) ?>"
                                                       class="level-1 p-1 block text-base font-semibold leading-loose
hover:underline">
                                                        <?= $escaper->escapeHtml($itemLevel2['name']) ?>
                                                    </a>

                                                    <ul class="z-10 w-full">
                                                        <?php foreach ($itemLevel2['childData'] as $itemLevel3): ?>
                                                            <li class="level-2">
                                                                <a href="<?= $escaper->escapeUrl($itemLevel3['url'])
?>"
                                                                   title="<?=
$escaper->escapeHtmlAttr($itemLevel3['name']) ?>"
                                                                   class="level-2 p-1 block text-lg md:text-sm
hover:underline"><?= $escaper->escapeHtml($itemLevel3['name']) ?></a>
                                                            </li>
                                                        <?php endforeach; ?>
                                                    </ul>

                                                </li>
                                            <?php endforeach; ?>
                                            <?php if ($singleItems): ?>
                                                <li class="level-1 min-w-48">
                                                    <?php foreach ($singleItems as $item): ?>
                                                        <a href="<?= $escaper->escapeUrl($item['url']) ?>"
                                                           title="<?= $escaper->escapeHtmlAttr($item['name']) ?>"
                                                           class="level-1 p-1 block text-base font-semibold
leading-loose hover:underline">
                                                            <?= $escaper->escapeHtml($item['name']) ?>
                                                        </a>
                                                    <?php endforeach; ?>
                                                </li>
                                            <?php endif; ?>
                                        </ul>
                                    </div>
                                    <?php
                                    $cmsBlockHtml = $catIdLvl1
                                        ? $this->getLayout()
                                               ->createBlock(CmsBlock::class)
                                               ->setBlockId('megamenu_block_right_cat' . $catIdLvl1)
                                               ->toHtml()
                                        : '';

                                    if (! empty($cmsBlockHtml)): ?>
                                    <div class="max-w-xs 2xl:block">
                                        <?= /** @noEscape */ $cmsBlockHtml ?>
                                    </div>
                                    <?php endif; ?>
                                </div>
                            </div>
                        <?php endif; ?>
                    </li>
                <?php endforeach; ?>
            </ul>
        </nav>
    </div>

</div>
<script>
  'use strict';

  const initMenuDesktop<?= $escaper->escapeHtml($uniqueId) ?> = () => {
    return {
      hoverTopPosition: '100%',
      setActiveMenu(menuNode) {
        Array.from(menuNode.querySelectorAll('a')).filter(link => {
          return link.href === window.location.href.split('?')[0];
        }).map(item => {
          if (!item.classList.contains('level-0')) {
            item.classList.add('underline');
          }
          item.closest('div.level-0') &&
          item.closest('div.level-0').classList.add('border-secondary');
        });
      }
    }
  }
</script>

