<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\ProductAttributes;
use Hyva\Theme\ViewModel\ProductCompare;
use Hyva\Theme\ViewModel\ProductPage;
use Hyva\Theme\ViewModel\Wishlist;
use Magento\Catalog\Model\Product;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @var Template $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */

/** @var ProductPage $productViewModel */
$productViewModel = $viewModels->require(ProductPage::class);
/** @var ProductAttributes $attributesViewModel */
$attributesViewModel = $viewModels->require(ProductAttributes::class);
/** @var Product $product */
$product = $productViewModel->getProduct();
$productType = $product->getTypeId();

?>
<div class="w-full mb-6">

    <div class="my-2 flex text-4xl font-bold">
        <?= $productViewModel->getProduct()->getName(); ?>
    </div>

    <div class="my-2 flex text-lg">
        Product Code : <?= $productViewModel->getProduct()->getSku(); ?>
    </div>

    <div role="group" aria-label="<?= $escaper->escapeHtmlAttr('Price') ?>">
        <?= $block->getChildHtml("product.info.price") ?>
    </div>

    <div class="my-2 flex text-xl">
        Delivery | Stock Message
    </div>

    <?= $block->getChildHtml('product.info.form') ?>

    <div class="flex flex-col sm:flex-row items-end my-4">

        <?php if ($productType === 'bundle'): ?>
            <span class="sr-only">
                <?= $escaper->escapeHtml(__('The price depends on the chosen options')) ?>
            </span>
        <?php endif; ?>

        <div class="flex mt-4 w-full sm:mt-0">
            <?php if ($product->isSaleable()): ?>
                <?= $block->getChildHtml("product.info.quantity") ?>
                <?= $block->getChildHtml("product.info.addtocart") ?>
                <?= $block->getChildHtml('product.info.addtowishlist'); ?>
            <?php endif; ?>
        </div>

    </div>

    <?php if ($tierPriceBlock = $block->getChildHtml("product.price.tier")): ?>
        <div class="py-4 my-2 tier-price-container">
            <?= /** @noEscape */ $tierPriceBlock ?>
        </div>
    <?php endif; ?>

    <?php if ($shortDescription = $productViewModel->getShortDescription()) { ?>
        <div class="mb-4 leading-relaxed product-description prose"><?= /* @noEscape */ $shortDescription ?></div>
    <?php } ?>

    <?= $block->getChildHtml("product.info.additional") ?>
</div>
