<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Magento\Framework\View\Element\Template;
use Magento\Framework\Escaper;
use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HeroiconsOutline;
use Hyva\Theme\ViewModel\ReCaptcha;
use Hyva\Theme\ViewModel\SvgIcons;
use Hyva\PaymentIcons\ViewModel\PaymentIconsLight;
use Magento\Framework\Exception\LocalizedException;
use Magento\Newsletter\Block\Subscribe;

/** @var Template $block */
/** @var Escaper $escaper */
/** @var Subscribe $newsletterBlock */
/** @var ViewModelRegistry $viewModels */
/** @var HeroiconsOutline $heroIcons */
/** @var SvgIcons $icons */
/** @var PaymentIconsLight $paymentIcons */

$icons = $viewModels->require(SvgIcons::class);
$paymentIcons = $viewModels->require(PaymentIconsLight::class);
$heroIcons = $viewModels->require(HeroiconsOutline::class);
$newsletterBlock = $block->getLayout()->createBlock(Subscribe::class);
$recaptcha = $newsletterBlock->getData('viewModelRecaptcha');

$items = [

    [
        'url'          => $block->getUrl('home'),
        'svg'          => $icons->renderHtml('lorum-logo-3', '', 170, 52)
    ],
    [
        'url'          => $block->getUrl('home'),
        'svg'          => $icons->renderHtml('lorum-logo-4', '', 170, 88)
    ],
    [
        'url'          => $block->getUrl('home'), // optional
        'svg'          => $icons->renderHtml('lorum-logo-1', '', 170, 38)
    ],
    [
        'url'          => $block->getUrl('home'),
        'svg'          => $icons->renderHtml('lorum-logo-2', '', 170, 38)
    ],
];
$itemIndex = 1;
$isHomePage = $block->getRequest()->getFullActionName() === 'cms_index_index';
?>

<?php if ($isHomePage): ?>
<div class="my-20 px-10">
    <div class="mb-4 sm:flex sm:justify-between sm:items-baseline">
        <div class="text-3xl leading-9 font-bold text-gray-800">
            Our favourite brands
        </div>
        <a
            href="<?= $escaper->escapeUrl($block->getUrl('#')) ?>"
            class="text-primaryBg hover:text-gray-800 text-lg leading-7 font-semibold"
        >
            Browse all brands →
        </a>
    </div>

    <div class="border-gray-300 border-t border-b py-5 flex mx-auto items-center">
        <div x-data="carousel()"
             x-id="['carousel-end', 'carousel-desc']"
             role="group"
             class="relative overflow-hidden min-w-full"
             aria-roledescription="<?= $escaper->escapeHtml(__('Carousel')) ?>"
             aria-label="<?= $escaper->escapeHtml(__('Our favourite brands')) ?>"
             :aria-describedby="$id('carousel-desc')"
        >
            <span
                class="sr-only"
                :id="$id('carousel-desc')"
                tabindex="-1"
            >
                <?= $escaper->escapeHtml(__('Navigating through the elements of the carousel is possible using the
tab key. You can skip the carousel using the skip link.')) ?>
            </span>
            <a
                :href="`#${$id('carousel-end')}`"
                class="action skip sr-only focus:not-sr-only focus:absolute focus:z-30 focus:bg-white"
            >
                <?= $escaper->escapeHtml(__('Press to skip the carousel')) ?>
            </a>
            <div x-ref="container" class="snap gap-3 flex overflow-x-scroll">
                <?php foreach ($items as $item): ?>
                    <div class="slide flex-auto grow-0 shrink-0 w-[calc(50%-6px)] flex
                                justify-center items-center md:w-[calc(25%-9px)]"
                         aria-roledescription="<?= $escaper->escapeHtml(__('Carousel item')) ?>"
                         :aria-hidden="!visibleElements.includes($el)"
                         aria-label="<?= $escaper->escapeHtmlAttr(__('Item %1 of %2', $itemIndex++, count($items)))
                         ?>"
                         @focusin="stop()"
                    >
                        <?php if ($item['url'] ?? false): ?>
                        <a href="<?= $escaper->escapeUrl($item['url'])?>">
                            <?php endif; ?>

                            <?php if ($item['svg'] ?? false): ?>
                                <?= $item['svg'] ?>
                            <?php elseif ($item['image_url'] ?? false): ?>
                                <img src="<?= $escaper->escapeHtmlAttr($item['image_url']) ?>"
                                     alt="<?= $escaper->escapeHtmlAttr($item['alt'] ?? '') ?>"
                                     width="<?= $escaper->escapeHtmlAttr($item['image_width'] ?? '') ?>"
                                     height="<?= $escaper->escapeHtmlAttr($item['image_height'] ?? '') ?>"
                                     loading="lazy"
                                />
                            <?php endif; ?>

                            <?php if ($item['url'] ?? false): ?>
                        </a>
                    <?php endif; ?>

                    </div>
                <?php endforeach; ?>
            </div>
            <span :id="$id('carousel-end')" tabindex="-1"></span>
        </div>
    </div>
</div>
<?php endif; ?>

<div class="text-gray-600 text-base leading-6 bg-gray-50 relative">
    <div class="bg-primaryBg text-gray-50 sm:flex p-7 text-center lg:text-left">
        <div class="flex justify-center sm:block lg:justify-end">
            <?= $icons->renderHtml('text-balloons', '', 84, 84, ['aria-hidden' => 'true']) ?>
        </div>
        <div class="max-w-md sm:pl-7">
            <div class="uppercase font-bold mb-4">
                <?= $escaper->escapeHtml(__('We’re happy to help')) ?>
            </div>
            <div>
                <?= $escaper->escapeHtml(
                    __(
                        'View our <a class="underline" href="%1">frequently asked questions</a>, <a class="underline"
href="%2">track your order</a> or <a class="underline" href="%3">get in touch</a> with any question you might have.',
                        $block->getUrl('#'),
                        $block->getUrl('sales/order/history'),
                        $block->getUrl('contact')
                    ), ['a']
                ) ?>
            </div>
        </div>
    </div>

    <div class="px-7 py-7 lg:absolute lg:right-0 lg:top-0">
        <div class="text-center uppercase font-bold lg:text-white lg:text-right">
            <?= $escaper->escapeHtml(__('Follow us')) ?>
        </div>
        <div class="flex justify-center gap-4 py-8 text-blue-800 border-b border-gray-300
                    lg:py-4 lg:border-0 lg:text-[#1C1917] lg:invert"
        >
            <a
                href="#"
                class="hover:opacity-80"
                aria-label="<?= $escaper->escapeHtmlAttr(__('Facebook')) ?>"
            >
                <?= $icons->renderHtml('social-facebook', 'w-12 h-auto lg:w-10', 32, 32, ['aria-hidden' => 'true', 'fill' => '#555656'])
?>
            </a>
            <a
                href="#"
                class="hover:opacity-80"
                aria-label="<?= $escaper->escapeHtmlAttr(__('Instagram')) ?>"
            >
                <?= $icons->renderHtml('social-instagram', 'w-12 h-auto lg:w-10', 32, 32, ['aria-hidden' => 'true'])
?>
            </a>
        </div>
    </div>

    <div class="container mx-auto px-7 lg:mt-8 lg:mb-8 flex justify-center items-center flex-col lg:flex-row">
        <div class="text-center">
            <div class="uppercase font-bold mb-3 text-gray-700">
                <?= $escaper->escapeHtml(__('Be the first to know')) ?>
            </div>
            <div>
                <?= $escaper->escapeHtml(__('Subscribe for the latest news and our best offers.')) ?>
            </div>
        </div>

        <form class="my-8 md:flex md:max-w-2xl md:mx-auto w-full"
              action="<?= $escaper->escapeUrl($newsletterBlock->getFormActionUrl()) ?>"
              method="post"
              x-data="initNewsletterForm()"
              @submit.prevent="submitForm()"
              id="newsletter-validate-detail"
        >
            <label class="sr-only"
                   for="newsletter-subscribe"
                   aria-label="<?= $escaper->escapeHtmlAttr(__('Email address')) ?>"
            >
                <?= $escaper->escapeHtml(__('Email address')) ?>
            </label>
            <input type="email"
                   name="email"
                   id="newsletter-subscribe"
                   required
                   placeholder="<?= $escaper->escapeHtmlAttr(__('Enter your email address')) ?>"
                   class="border-gray-300 bg-white w-full p-3 mb-2 border rounded-md shadow-sm
                          placeholder:text-gray-400 outline-none focus:ring-primaryBg focus:ring-1
                          md:w-auto md:grow md:mb-0 md:mr-2"
            />
            <?= $newsletterBlock->getBlockHtml('formkey') ?>
            <input type="submit"
                   value="<?= $escaper->escapeHtmlAttr(__('Subscribe')) ?>"
                   class="bg-primaryBg p-3 cursor-pointer w-full border border-blue-700 rounded-md shadow-sm text-white hover:bg-opacity-90 md:flex-1"
            />
            <?= $recaptcha ? $recaptcha->getInputHtml(ReCaptcha::RECAPTCHA_FORM_ID_NEWSLETTER) : '' ?>
            <div>
                <template x-if="displayErrorMessage">
                    <p class="flex items-center text-red">
                        <span class="inline-block w-8 h-8 mr-3">
                            <?= $heroIcons->exclamationCircleHtml('', 24, 24, ['aria-hidden' => 'true']) ?>
                        </span>
                        <template x-for="errorMessage in errorMessages">
                            <span x-html="errorMessage"></span>
                        </template>
                    </p>
                </template>
            </div>

        </form>
        <div>
            <?= $recaptcha ? $recaptcha->getLegalNoticeHtml(ReCaptcha::RECAPTCHA_FORM_ID_NEWSLETTER) : '' ?>
        </div>
    </div>

    <div class="bg-primaryBg text-gray-200 py-8 border-b border-gray-300">
        <div class="container mx-auto px-7 divide-gray-200 divide-y space-y-4
                    lg:flex lg:divide-none lg:justify-between lg:space-y-0">
            <?php
            $columns = [];
            for ($i=1; $i<5; $i++):
                try {
                    $columns[$i] = $block->getLayout()
                        ->createBlock(Magento\Cms\Block\BlockByIdentifier::class)
                        ->addData(['identifier' => 'footer_column_' . $i])
                        ->toHtml();
                } catch (LocalizedException $e) {
                    $columns[$i] = false;
                }
            endfor; ?>

            <div x-data="{ open: false }">
                <?php if ($columns[1]): ?>
                    <?= /** @noEscape */ $columns[1] ?>
                <?php else: ?>
                    <a @click="open = ! open"
                       class="flex justify-between align-middle cursor-pointer group lg:cursor-default"
                    >
                        <h4 class="uppercase font-bold text-gray-200 group-hover:underline
lg:group-hover:no-underline">
                            <?= $escaper->escapeHtml(__('Weybridge Lights')) ?>
                        </h4>
                        <span class="transition-transform" :class="{ 'rotate-180': open }">
                            <?= $heroIcons->chevronDownHtml('text-gray-500 stroke-current lg:hidden', 24, 24 ,
['aria-hidden' => 'true']) ?>
                        </span>
                    </a>
                    <ul class="flex-col gap-2 mt-4 mb-6 lg:flex" :class="{ 'flex': open, 'hidden': ! open }">
                        <li>
                            4-5 The Old Cow Shed,<br> Cobham Park Estate,<br> Cobham Park Road,<br> Cobham, Surrey<br> KT11 3NE
                        </li>
                        <br><br><br>
                        <li>
                            <?= $escaper->escapeHtml(__('Tel. 01932 820318')) ?>
                        </li>
                        <li>
                            <a
                                href="<?= $escaper->escapeUrl($block->getUrl('home')) ?>"
                                class="hover:underline"
                            >
                                <?= $escaper->escapeHtml(__('Sales@weybridgelights.co.uk')) ?>
                            </a>
                        </li>
                    </ul>
                <?php endif; ?>
            </div>
            <div x-data="{ open: false }" class="pt-4 lg:p-0">
                <?php if ($columns[2]): ?>
                    <?= /** @noEscape */ $columns[2] ?>
                <?php else: ?>
                    <a @click="open = ! open"
                       class="flex justify-between align-middle cursor-pointer group lg:cursor-default"
                    >
                        <h4 class="uppercase font-bold text-gray-200 group-hover:underline
lg:group-hover:no-underline">
                            <?= $escaper->escapeHtml(__('Customer Care')) ?>
                        </h4>
                        <span class="transition-transform" :class="{ 'rotate-180': open }">
                            <?= $heroIcons->chevronDownHtml('text-gray-500 stroke-current lg:hidden', 24, 24,
['aria-hidden' => 'true']) ?>
                        </span>
                    </a>
                    <ul class="flex-col gap-2 mt-4 mb-6 lg:flex" :class="{ 'flex': open, 'hidden': ! open }">
                        <li>
                            <a
                                href="<?= $escaper->escapeUrl($block->getUrl('home')) ?>"
                                class="hover:underline"
                            >
                                <?= $escaper->escapeHtml(__('Home')) ?>
                            </a>
                        </li>
                        <li>
                            <a
                                href="<?= $escaper->escapeUrl($block->getUrl('contact')) ?>"
                                class="hover:underline"
                            >
                                <?= $escaper->escapeHtml(__('Contact')) ?>
                            </a>
                        </li>
                        <li>
                            <a
                                href="<?= $escaper->escapeUrl($block->getUrl('home')) ?>"
                                class="hover:underline"
                            >
                                <?= $escaper->escapeHtml(__('Site Map')) ?>
                            </a>
                        </li>
                        <li>
                            <a
                                href="<?= $escaper->escapeUrl($block->getUrl('home')) ?>"
                                class="hover:underline"
                            >
                                <?= $escaper->escapeHtml(__('Delivery Information')) ?>
                            </a>
                        </li>
                        <li>
                            <a
                                href="<?= $escaper->escapeUrl($block->getUrl('home')) ?>"
                                class="hover:underline"
                            >
                                <?= $escaper->escapeHtml(__('Terms & Conditions')) ?>
                            </a>
                        </li>
                        <li>
                            <a
                                href="<?= $escaper->escapeUrl($block->getUrl('home')) ?>"
                                class="hover:underline"
                            >
                                <?= $escaper->escapeHtml(__('Privacy Policy')) ?>
                            </a>
                        </li>
                        <li>
                            <a
                                href="<?= $escaper->escapeUrl($block->getUrl('home')) ?>"
                                class="hover:underline"
                            >
                                <?= $escaper->escapeHtml(__('Our Showroom')) ?>
                            </a>
                        </li>
                        <li>
                            <a
                                href="<?= $escaper->escapeUrl($block->getUrl('home')) ?>"
                                class="hover:underline"
                            >
                                <?= $escaper->escapeHtml(__('GDPR Tools')) ?>
                            </a>
                        </li>
                    </ul>
                <?php endif; ?>
            </div>
            <div x-data="{ open: false }" class="pt-4 lg:p-0">
                <?php if ($columns[3]): ?>
                    <?= /** @noEscape */ $columns[3] ?>
                <?php else: ?>
                    <a @click="open = ! open"
                       class="flex justify-between align-middle cursor-pointer group lg:cursor-default"
                    >
                        <h4 class="uppercase font-bold text-gray-200 group-hover:underline
lg:group-hover:no-underline">
                            <?= $escaper->escapeHtml(__('Services')) ?>
                        </h4>
                        <span class="transition-transform" :class="{ 'rotate-180': open }">
                            <?= $heroIcons->chevronDownHtml('text-gray-500 stroke-current lg:hidden', 24, 24,
['aria-hidden' => 'true']) ?>
                        </span>
                    </a>
                    <ul class="flex-col gap-2 mt-4 mb-6 lg:flex" :class="{ 'flex': open, 'hidden': ! open }">
                        <li>
                            <a
                                href="<?= $escaper->escapeUrl($block->getUrl('home')) ?>"
                                class="hover:underline"
                            >
                                <?= $escaper->escapeHtml(__('Trade Accounts')) ?>
                            </a>
                        </li>
                        <li>
                            <a
                                href="<?= $escaper->escapeUrl($block->getUrl('home')) ?>"
                                class="hover:underline"
                            >
                                <?= $escaper->escapeHtml(__('Lighting Controls & Design')) ?>
                            </a>
                        </li>
                        <li>
                            <a
                                href="<?= $escaper->escapeUrl($block->getUrl('home')) ?>"
                                class="hover:underline"
                            >
                                <?= $escaper->escapeHtml(__('Luxury Home Golf Simulator')) ?>
                            </a>
                        </li>
                        <li>
                            <a
                                href="<?= $escaper->escapeUrl($block->getUrl('home')) ?>"
                                class="hover:underline"
                            >
                                <?= $escaper->escapeHtml(__('Lighting Design')) ?>
                            </a>
                        </li>
                        <li>
                            <a
                                href="<?= $escaper->escapeUrl($block->getUrl('home')) ?>"
                                class="hover:underline"
                            >
                                <?= $escaper->escapeHtml(__('Bespoke Lighting')) ?>
                            </a>
                        </li>
                        <li>
                            <a
                                href="<?= $escaper->escapeUrl($block->getUrl('home')) ?>"
                                class="hover:underline"
                            >
                                <?= $escaper->escapeHtml(__('Sourcing')) ?>
                            </a>
                        </li>
                    </ul>
                <?php endif; ?>
            </div>
            <div x-data="{ open: false }" class="pt-4 lg:p-0">
                <?php if ($columns[4]): ?>
                    <?= /** @noEscape */ $columns[4] ?>
                <?php else: ?>
                    <a @click="open = ! open"
                       class="flex justify-between align-middle cursor-pointer group lg:cursor-default"
                    >
                        <h4 class="uppercase font-bold text-gray-200 group-hover:underline
lg:group-hover:no-underline">
                            <?= $escaper->escapeHtml(__('Popular Categories')) ?>
                        </h4>
                        <span class="transition-transform" :class="{ 'rotate-180': open }">
                            <?= $heroIcons->chevronDownHtml('text-gray-500 stroke-current lg:hidden', 24, 24,
['aria-hidden' => 'true']) ?>
                        </span>
                    </a>
                    <ul class="flex-col gap-2 mt-4 mb-6 lg:flex" :class="{ 'flex': open, 'hidden': ! open }">
                        <li>
                            <a
                                href="<?= $escaper->escapeUrl($block->getUrl('home')) ?>"
                                class="hover:underline">
                                <?= $escaper->escapeHtml(__('Schonbex Lighting')) ?>
                            </a>
                        </li>
                        <li>
                            <a
                                href="<?= $escaper->escapeUrl($block->getUrl('home')) ?>"
                                class="hover:underline">
                                <?= $escaper->escapeHtml(__('Lodes')) ?>
                            </a>
                        </li>
                        <li>
                            <a
                                href="<?= $escaper->escapeUrl($block->getUrl('home')) ?>"
                                class="hover:underline">
                                <?= $escaper->escapeHtml(__('Stairwell Lights')) ?>
                            </a>
                        </li>
                        <li>
                            <a
                                href="<?= $escaper->escapeUrl($block->getUrl('home')) ?>"
                                class="hover:underline">
                                <?= $escaper->escapeHtml(__('Weybridge Lights Projects')) ?>
                            </a>
                        </li>
                        <li>
                            <a
                                href="<?= $escaper->escapeUrl($block->getUrl('home')) ?>"
                                class="hover:underline">
                                <?= $escaper->escapeHtml(__('Crystal Lighting')) ?>
                            </a>
                        </li>
                        <li>
                            <a
                                href="<?= $escaper->escapeUrl($block->getUrl('home')) ?>"
                                class="hover:underline">
                                <?= $escaper->escapeHtml(__('Masiero Lighting')) ?>
                            </a>
                        </li>
                    </ul>
                <?php endif; ?>
            </div>
        </div>
    </div>

    <div class="border-t border-gray-300 bg-gray-100">
        <div class="py-4 text-sm sm:flex sm:justify-between container mx-auto px-7">
            <div class="text-gray-500 flex justify-center items-center">
                <?= $escaper->escapeHtml(__('Copyright © 2024, Weybridge Lights, All Rights Reserved')) ?>
            </div>
            <div class="text-gray-400 mt-2 sm:mt-0">
                <div class="text-center flex gap-4 flex-wrap justify-center">
                    <?= $paymentIcons->americanExpressHtml('', 48, 32, ['aria-hidden' => 'true']) ?>
                    <?= $paymentIcons->applePayHtml('', 48, 32, ['aria-hidden' => 'true']) ?>
                    <?= $paymentIcons->mastercardHtml('', 48, 32, ['aria-hidden' => 'true']) ?>
                    <?= $paymentIcons->paypalHtml('', 48, 32, ['aria-hidden' => 'true']) ?>
                    <?= $paymentIcons->visaHtml('', 48, 32, ['aria-hidden' => 'true']) ?>
                </div>
            </div>
        </div>
    </div>

    <script>
        function initNewsletterForm() {
            return {
                errors: 0,
                hasCaptchaToken: 0,
                displayErrorMessage: false,
                errorMessages: [],
                setErrorMessages(messages) {
                    this.errorMessages = [messages]
                    this.displayErrorMessage = this.errorMessages.length
                },
                submitForm() {
                    const $form = document.querySelector('#newsletter-validate-detail');
                    <?= $newsletterBlock->getChildHtml('recaptcha_validation_newsletter'); ?>

                    if (this.errors === 0) {
                        $form.submit();
                    }
                }
            }
        }
    </script>
</div>

