<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Magento\Framework\View\Element\Template;
use Magento\Framework\Escaper;
use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HeroiconsOutline;
use Hyva\Theme\ViewModel\ReCaptcha;
use Hyva\Theme\ViewModel\SvgIcons;
use Hyva\PaymentIcons\ViewModel\PaymentIconsLight;
use Magento\Framework\Exception\LocalizedException;
use Magento\Newsletter\Block\Subscribe;

/** @var Template $block */
/** @var Escaper $escaper */
/** @var Subscribe $newsletterBlock */
/** @var ViewModelRegistry $viewModels */
/** @var HeroiconsOutline $heroIcons */
/** @var SvgIcons $icons */
/** @var PaymentIconsLight $paymentIcons */

$icons = $viewModels->require(SvgIcons::class);
$paymentIcons = $viewModels->require(PaymentIconsLight::class);
$heroIcons = $viewModels->require(HeroiconsOutline::class);
$newsletterBlock = $block->getLayout()->createBlock(Subscribe::class);
$recaptcha = $newsletterBlock->getData('viewModelRecaptcha');
?>
<div class="text-gray-600 text-base leading-6 bg-gray-50 relative">
    <div class="bg-blue-900 text-gray-50 sm:flex p-7">
        <div class="flex justify-end sm:block">
            <?= $icons->renderHtml('text-balloons', '', 84, 84, ['aria-hidden' => 'true']) ?>
        </div>
        <div class="max-w-md sm:pl-7">
            <div class="uppercase font-bold mb-4">
                <?= $escaper->escapeHtml(__('We’re happy to help')) ?>
            </div>
            <div>
                <?= $escaper->escapeHtml(
                    __(
                        'View our <a class="underline" href="%1">frequently asked questions</a>, <a class="underline" 
href="%2">track your order</a> or <a class="underline" href="%3">get in touch</a> with any question you might have.',
                        $block->getUrl('#'),
                        $block->getUrl('sales/order/history'),
                        $block->getUrl('contact')
                    ), ['a']
                ) ?>
            </div>
        </div>
    </div>

    <div class="px-7 py-7 lg:absolute lg:right-0 lg:top-0">
        <div class="text-center uppercase font-bold lg:text-white lg:text-right">
            <?= $escaper->escapeHtml(__('Follow us')) ?>
        </div>
        <div class="flex justify-center gap-4 py-8 text-blue-800 border-b border-gray-300
                    lg:py-4 lg:border-0 lg:text-[#1C1917] lg:invert"
        >
            <a
                href="#"
                class="hover:opacity-80"
                aria-label="<?= $escaper->escapeHtmlAttr(__('Facebook')) ?>"
            >
                <?= $icons->renderHtml('social-facebook', 'w-12 h-auto lg:w-10', 32, 32, ['aria-hidden' => 'true']) 
?>
            </a>
            <a
                href="#"
                class="hover:opacity-80"
                aria-label="<?= $escaper->escapeHtmlAttr(__('Instagram')) ?>"
            >
                <?= $icons->renderHtml('social-instagram', 'w-12 h-auto lg:w-10', 32, 32, ['aria-hidden' => 'true']) 
?>
            </a>
            <a
                href="#"
                class="hover:opacity-80"
                aria-label="<?= $escaper->escapeHtmlAttr(__('Pinterest')) ?>"
            >
                <?= $icons->renderHtml('social-pinterest', 'w-12 h-auto lg:w-10', 32, 32, ['aria-hidden' => 'true']) 
?>
            </a>
            <a
                href="#"
                class="hover:opacity-80"
                aria-label="<?= $escaper->escapeHtmlAttr(__('Twitter')) ?>"
            >
                <?= $icons->renderHtml('social-twitter', 'w-12 h-auto lg:w-10', 32, 32, ['aria-hidden' => 'true']) ?>
            </a>
        </div>
    </div>

    <div class="container mx-auto px-7 lg:mt-8">
        <div class="text-center">
            <div class="uppercase font-bold mb-3 text-gray-700">
                <?= $escaper->escapeHtml(__('Be the first to know')) ?>
            </div>
            <div>
                <?= $escaper->escapeHtml(__('Subscribe for the latest news and our best offers.')) ?>
            </div>
        </div>

        <form class="my-8 md:flex md:max-w-2xl md:mx-auto"
              action="<?= $escaper->escapeUrl($newsletterBlock->getFormActionUrl()) ?>"
              method="post"
              x-data="initNewsletterForm()"
              @submit.prevent="submitForm()"
              id="newsletter-validate-detail"
        >
            <label class="sr-only"
                   for="newsletter-subscribe"
                   aria-label="<?= $escaper->escapeHtmlAttr(__('Email address')) ?>"
            >
                <?= $escaper->escapeHtml(__('Email address')) ?>
            </label>
            <input type="email"
                   name="email"
                   id="newsletter-subscribe"
                   required
                   placeholder="<?= $escaper->escapeHtmlAttr(__('Enter your email address')) ?>"
                   class="border-gray-300 bg-white w-full p-3 mb-2 border rounded-md shadow-sm
                          placeholder:text-gray-400 outline-none focus:ring-blue-700 focus:ring-1
                          md:w-auto md:grow md:mb-0 md:mr-2"
            />
            <?= $newsletterBlock->getBlockHtml('formkey') ?>
            <input type="submit"
                   value="<?= $escaper->escapeHtmlAttr(__('Subscribe')) ?>"
                   class="bg-blue-700 p-3 cursor-pointer w-full border border-blue-700 rounded-md shadow-sm 
text-white
                          hover:bg-opacity-90 md:flex-1"
            />
            <?= $recaptcha ? $recaptcha->getInputHtml(ReCaptcha::RECAPTCHA_FORM_ID_NEWSLETTER) : '' ?>
            <div>
                <template x-if="displayErrorMessage">
                    <p class="flex items-center text-red">
                        <span class="inline-block w-8 h-8 mr-3">
                            <?= $heroIcons->exclamationCircleHtml('', 24, 24, ['aria-hidden' => 'true']) ?>
                        </span>
                        <template x-for="errorMessage in errorMessages">
                            <span x-html="errorMessage"></span>
                        </template>
                    </p>
                </template>
            </div>

        </form>
        <div class="w-full">
            <?= $recaptcha ? $recaptcha->getLegalNoticeHtml(ReCaptcha::RECAPTCHA_FORM_ID_NEWSLETTER) : '' ?>
        </div>
    </div>

    <div class="bg-gray-100 py-8 border-b border-gray-300">
        <div class="container mx-auto px-7 divide-gray-200 divide-y space-y-4
                    lg:flex lg:divide-none lg:justify-between lg:space-y-0">
            <?php
            $columns = [];
            for ($i=1; $i<5; $i++):
                try {
                    $columns[$i] = $block->getLayout()
                        ->createBlock(Magento\Cms\Block\BlockByIdentifier::class)
                        ->addData(['identifier' => 'footer_column_' . $i])
                        ->toHtml();
                } catch (LocalizedException $e) {
                    $columns[$i] = false;
                }
            endfor; ?>

            <div x-data="{ open: false }">
                <?php if ($columns[1]): ?>
                    <?= /** @noEscape */ $columns[1] ?>
                <?php else: ?>
                    <a @click="open = ! open"
                       class="flex justify-between align-middle cursor-pointer group lg:cursor-default"
                    >
                        <h4 class="uppercase font-bold text-gray-700 group-hover:underline 
lg:group-hover:no-underline">
                            <?= $escaper->escapeHtml(__('Shop')) ?>
                        </h4>
                        <span class="transition-transform" :class="{ 'rotate-180': open }">
                            <?= $heroIcons->chevronDownHtml('text-gray-500 stroke-current lg:hidden', 24, 24 , 
['aria-hidden' => 'true']) ?>
                        </span>
                    </a>
                    <ul class="flex-col gap-4 mt-4 mb-6 lg:flex" :class="{ 'flex': open, 'hidden': ! open }">
                        <li>
                            <a
                                href="<?= $escaper->escapeUrl($block->getUrl('home')) ?>"
                                class="hover:underline"
                            >
                                <?= $escaper->escapeHtml(__('What\'s new')) ?>
                            </a>
                        </li>
                        <li>
                            <a
                                href="<?= $escaper->escapeUrl($block->getUrl('home')) ?>"
                                class="hover:underline"
                            >
                                <?= $escaper->escapeHtml(__('Women')) ?>
                            </a>
                        </li>
                        <li>
                            <a
                                href="<?= $escaper->escapeUrl($block->getUrl('home')) ?>"
                                class="hover:underline"
                            >
                                <?= $escaper->escapeHtml(__('Men')) ?>
                            </a>
                        </li>
                        <li>
                            <a
                                href="<?= $escaper->escapeUrl($block->getUrl('home')) ?>"
                                class="hover:underline"
                            >
                                <?= $escaper->escapeHtml(__('Gear')) ?>
                            </a>
                        </li>
                        <li>
                            <a
                                href="<?= $escaper->escapeUrl($block->getUrl('home')) ?>"
                                class="hover:underline"
                            >
                                <?= $escaper->escapeHtml(__('Training')) ?>
                            </a>
                        </li>
                        <li>
                            <a
                                href="<?= $escaper->escapeUrl($block->getUrl('home')) ?>"
                                class="hover:underline"
                            >
                                <?= $escaper->escapeHtml(__('Sale')) ?>
                            </a>
                        </li>
                    </ul>
                <?php endif; ?>
            </div>
            <div x-data="{ open: false }" class="pt-4 lg:p-0">
                <?php if ($columns[2]): ?>
                    <?= /** @noEscape */ $columns[2] ?>
                <?php else: ?>
                    <a @click="open = ! open"
                       class="flex justify-between align-middle cursor-pointer group lg:cursor-default"
                    >
                        <h4 class="uppercase font-bold text-gray-700 group-hover:underline 
lg:group-hover:no-underline">
                            <?= $escaper->escapeHtml(__('Customer service')) ?>
                        </h4>
                        <span class="transition-transform" :class="{ 'rotate-180': open }">
                            <?= $heroIcons->chevronDownHtml('text-gray-500 stroke-current lg:hidden', 24, 24, 
['aria-hidden' => 'true']) ?>
                        </span>
                    </a>
                    <ul class="flex-col gap-4 mt-4 mb-6 lg:flex" :class="{ 'flex': open, 'hidden': ! open }">
                        <li>
                            <a
                                href="<?= $escaper->escapeUrl($block->getUrl('home')) ?>"
                                class="hover:underline"
                            >
                                <?= $escaper->escapeHtml(__('Shipment of your order')) ?>
                            </a>
                        </li>
                        <li>
                            <a
                                href="<?= $escaper->escapeUrl($block->getUrl('home')) ?>"
                                class="hover:underline"
                            >
                                <?= $escaper->escapeHtml(__('Payment options')) ?>
                            </a>
                        </li>
                        <li>
                            <a
                                href="<?= $escaper->escapeUrl($block->getUrl('home')) ?>"
                                class="hover:underline"
                            >
                                <?= $escaper->escapeHtml(__('Returns and replacements')) ?>
                            </a>
                        </li>
                        <li>
                            <a
                                href="<?= $escaper->escapeUrl($block->getUrl('home')) ?>"
                                class="hover:underline"
                            >
                                <?= $escaper->escapeHtml(__('Warranty and repairs')) ?>
                            </a>
                        </li>
                        <li>
                            <a
                                href="<?= $escaper->escapeUrl($block->getUrl('home')) ?>"
                                class="hover:underline"
                            >
                                <?= $escaper->escapeHtml(__('Get in touch')) ?>
                            </a>
                        </li>
                    </ul>
                <?php endif; ?>
            </div>
            <div x-data="{ open: false }" class="pt-4 lg:p-0">
                <?php if ($columns[3]): ?>
                    <?= /** @noEscape */ $columns[3] ?>
                <?php else: ?>
                    <a @click="open = ! open"
                       class="flex justify-between align-middle cursor-pointer group lg:cursor-default"
                    >
                        <h4 class="uppercase font-bold text-gray-700 group-hover:underline 
lg:group-hover:no-underline">
                            <?= $escaper->escapeHtml(__('Our company')) ?>
                        </h4>
                        <span class="transition-transform" :class="{ 'rotate-180': open }">
                            <?= $heroIcons->chevronDownHtml('text-gray-500 stroke-current lg:hidden', 24, 24, 
['aria-hidden' => 'true']) ?>
                        </span>
                    </a>
                    <ul class="flex-col gap-4 mt-4 mb-6 lg:flex" :class="{ 'flex': open, 'hidden': ! open }">
                        <li>
                            <a
                                href="<?= $escaper->escapeUrl($block->getUrl('about-us')) ?>"
                                class="hover:underline"
                            >
                                <?= $escaper->escapeHtml(__('About us')) ?>
                            </a>
                        </li>
                        <li>
                            <a
                                href="<?= $escaper->escapeUrl($block->getUrl('home')) ?>"
                                class="hover:underline"
                            >
                                <?= $escaper->escapeHtml(__('Blog')) ?>
                            </a>
                        </li>
                        <li>
                            <a
                                href="<?= $escaper->escapeUrl($block->getUrl('home')) ?>"
                                class="hover:underline"
                            >
                                <?= $escaper->escapeHtml(__('Our stores')) ?>
                            </a>
                        </li>
                        <li>
                            <a
                                href="<?= $escaper->escapeUrl($block->getUrl('home')) ?>"
                                class="hover:underline"
                            >
                                <?= $escaper->escapeHtml(__('Sustainability')) ?>
                            </a>
                        </li>
                    </ul>
                <?php endif; ?>
            </div>
            <div x-data="{ open: false }" class="pt-4 lg:p-0">
                <?php if ($columns[4]): ?>
                    <?= /** @noEscape */ $columns[4] ?>
                <?php else: ?>
                    <a @click="open = ! open"
                       class="flex justify-between align-middle cursor-pointer group lg:cursor-default"
                    >
                        <h4 class="uppercase font-bold text-gray-700 group-hover:underline 
lg:group-hover:no-underline">
                            <?= $escaper->escapeHtml(__('My account')) ?>
                        </h4>
                        <span class="transition-transform" :class="{ 'rotate-180': open }">
                            <?= $heroIcons->chevronDownHtml('text-gray-500 stroke-current lg:hidden', 24, 24, 
['aria-hidden' => 'true']) ?>
                        </span>
                    </a>
                    <ul class="flex-col gap-4 mt-4 mb-6 lg:flex" :class="{ 'flex': open, 'hidden': ! open }">
                        <li>
                            <a
                                href="<?= $escaper->escapeUrl($block->getUrl('customer/account')) ?>"
                                class="hover:underline">
                                <?= $escaper->escapeHtml(__('My account')) ?>
                            </a>
                        </li>
                        <li>
                            <a
                                href="<?= $escaper->escapeUrl($block->getUrl('sales/order/history')) ?>"
                                class="hover:underline"
                            >
                                <?= $escaper->escapeHtml(__('My orders')) ?>
                            </a>
                        </li>
                    </ul>
                <?php endif; ?>
            </div>
        </div>
    </div>

    <div class="py-8 container mx-auto px-7">

        <ul class="flex justify-center gap-11 mb-8">
            <li class="hidden lg:flex items-center gap-3">
                <?= $heroIcons->checkHtml('stroke-current text-green-500', 24, 24, ['aria-hidden' => 'true']) ?>
                <span><?= $escaper->escapeHtml(__('Shipped within a day')) ?></span>
            </li>
            <li class="flex items-center gap-3">
                <?= $heroIcons->checkHtml('stroke-current text-green-500', 24, 24, ['aria-hidden' => 'true']) ?>
                <span><?= $escaper->escapeHtml(__('Free shipping and returns')) ?></span>
            </li>
            <li class="hidden lg:flex items-center gap-3">
                <?= $heroIcons->checkHtml('stroke-current text-green-500', 24, 24, ['aria-hidden' => 'true']) ?>
                <span><?= $escaper->escapeHtml(__('Free returns')) ?></span>
            </li>
            <li class="hidden lg:flex items-center gap-3">
                <?= $heroIcons->checkHtml('stroke-current text-green-500', 24, 24, ['aria-hidden' => 'true']) ?>
                <span><?= $escaper->escapeHtml(__('Refer a friend and get a discount')) ?></span>
            </li>
        </ul>

        <div class="text-center flex gap-4 flex-wrap justify-center">
            <?= $paymentIcons->idealHtml('', 48, 32, ['aria-hidden' => 'true']) ?>
            <?= $paymentIcons->visaHtml('', 48, 32, ['aria-hidden' => 'true']) ?>
            <?= $paymentIcons->mastercardHtml('', 48, 32, ['aria-hidden' => 'true']) ?>
            <?= $paymentIcons->paypalHtml('', 48, 32, ['aria-hidden' => 'true']) ?>
            <?= $paymentIcons->klarnaHtml('', 48, 32, ['aria-hidden' => 'true']) ?>
            <?= $paymentIcons->applePayHtml('', 48, 32, ['aria-hidden' => 'true']) ?>
            <?= $paymentIcons->googlePayHtml('', 48, 32, ['aria-hidden' => 'true']) ?>
            <?= $paymentIcons->bitcoinHtml('', 48, 32, ['aria-hidden' => 'true']) ?>
        </div>
    </div>

    <div class="border-t border-gray-300 bg-gray-100">
        <div class="py-4 text-sm sm:flex sm:justify-between container mx-auto px-7">
            <div class="text-gray-500">
                <?= $escaper->escapeHtml(__('© 2022 Hyvä')) ?> -
                <?php /* Enable the following line to show the copyright information configured in the admin
                <?= $escaper->escapeHtml($block->getCopyright()) ?>
                */ ?>
                <a class="hover:underline"
                   href="<?= $escaper->escapeHtmlAttr('https://twitter.com/hyva_io') ?>"
                   target="_blank"
                   rel="noopener noreferrer"
                >
                    <?= $escaper->escapeHtml(__('@hyva_io')) ?>
                </a>
            </div>
            <div class="text-gray-400 mt-2 sm:mt-0">
                <a
                    href="<?= $escaper->escapeUrl($block->getUrl('privacy-policy-cookie-restriction-mode')) ?>"
                    class="hover:underline"
                >
                    <?= $escaper->escapeHtml(__('Terms & Conditions')) ?>
                </a> |
                <a
                    href="<?= $escaper->escapeUrl($block->getUrl('privacy-policy-cookie-restriction-mode')) ?>"
                    class="hover:underline"
                >
                    <?= $escaper->escapeHtml(__('Privacy Policy')) ?>
                </a>
            </div>
        </div>
    </div>

    <script>
        function initNewsletterForm() {
            return {
                errors: 0,
                hasCaptchaToken: 0,
                displayErrorMessage: false,
                errorMessages: [],
                setErrorMessages(messages) {
                    this.errorMessages = [messages]
                    this.displayErrorMessage = this.errorMessages.length
                },
                submitForm() {
                    const $form = document.querySelector('#newsletter-validate-detail');
                    <?= $newsletterBlock->getChildHtml('recaptcha_validation_newsletter'); ?>

                    if (this.errors === 0) {
                        $form.submit();
                    }
                }
            }
        }
    </script>
</div>

